### PR TITLE
adding license

### PR DESCRIPTION
**Pull request by obradovic**
@abhiyerra 

* just adding the copyright thingy

### CODE REVIEW

**Comment by vladlosev** [comment]
Wait, doesn't the 'All Rights Reserved' part actually contradict the MIT license?

**Comment by abhiyerra** [comment]
Believe this way is more appropriate.

**Comment by parkr** [comment]
@alextouma – what do you recommend here? Please see https://github.com/vsco/jsonconsul/pull/5/files

**Comment by parkr** [comment]
@alextouma wrote me:

> MIT is fine.

**Pull request merged**
